### ISSUE TITLE
How to use the Gateway via Docker image?

### ISSUE THREAD

**Issue by Nutomic** [storj/gateway-st#48]
I need to run the gateway inside a Docker image, and found [this one on Docker Hub](https://hub.docker.com/r/storjlabs/gateway). But I cant find any documentation for it, and I'm not sure how should be used. Based on the [Dockerfile](https://github.com/storj/storj/blob/c481e071b2727c606e89a6af1e9243bd5df828af/cmd/gateway/Dockerfile), I created the following docker-compose.yml entry:
```

  storj-gateway:
    image: storjlabs/gateway:4e85ae9a-v0.29.6-go1.13.5-amd64
    container_name: storj-gateway
    restart: always
    networks:
      - serverbase
    environment:
      - API_KEY=my-api-key
      - SATELLITE_ADDR=my-satellite-addr
```

But this is not working, the logs keep repeating the following error. It seems like the environment variables are not used by the container. What is the correct way to do this?
```
Please enter numeric choice or enter satellite address manually [1]: Enter your API key: Select your satellite:
[1] us-central-1.tardigrade.io
[2] europe-west-1.tardigrade.io
[3] asia-east-1.tardigrade.io
2020-01-13T14:38:45.838Z    FATAL   Unrecoverable error     {"error": "gateway setup error: API key cannot be empty", "errorVerbose": "gateway setup error: API key cannot be empty\n\tstorj.io/storj/cmd/internal/wizard.PromptForAPIKey:119\n\tmain.GatewayFlags.interactive:287\n\tmain.cmdSetup:127\n\tstorj.io/storj/pkg/process.cleanup.func1.2:278\n\tstorj.io/storj/pkg/process.cleanup.func1:296\n\tgithub.com/spf13/cobra.(*Command).execute:826\n\tgithub.com/spf13/cobra.(*Command).ExecuteC:914\n\tgithub.com/spf13/cobra.(*Command).Execute:864\n\tstorj.io/storj/pkg/process.Exec:74\n\tmain.main:365\n\truntime.main:203"}
```
