### ISSUE TITLE
Since Version 1.9.0 File deletion not working properly anymore

### ISSUE THREAD

**Issue by venomone** [storj/gateway-st#76]
Hello folks,

I'm using Storj Gateway x86_64 version 1.9.0. Since this version upgrade, mass deletion of files is not working properly anymore e.g. using S3 Browser. Bulk deletion simply fails with this version using some tools, I have no Idea why this is happening, but as soon as I have a couple of thousand file in a folder the whole process simply breaks, using the 1.8.x or any other previous version does not have this bug despite that I'm using s3.delete-objects-concurrency: 10000 or any higher or lower value ...

Any Idea?

**Comment by amwolff** [comment]
Can you try the lowest possible setting, i.e., `s3.delete-objects-concurrency`: `1`?

**Comment by venomone** [comment]
Just for reference, these are my settings:

```yaml
access: %STORJ_ACCESS%
minio.access-key: %S3_ACCESS_KEY%
minio.secret-key: %S3_SECRET_KEY%
server.address: 127.0.0.1:7777
advanced: false
website: false
s3.disable-copy-object: true
s3.include-custom-metadata-listing: true
s3.max-keys-exhaustive-limit: 10000000
s3.max-keys-limit: 1000000
s3.min-part-size: 8388608
s3.delete-objects-concurrency: 1
log.level: fatal
log.stack: false
```

The outcome using these settings is that it's not working again. To be honest, I never tried one, at least 100 or so.
Thanks for the hint.
